FROM node:20-alpine

WORKDIR /app

ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

COPY package.json package-lock.json ./
COPY tsconfig.base.json ./
COPY apps/web/package.json ./apps/web/package.json
COPY apps/api/package.json ./apps/api/package.json

RUN npm ci

COPY apps/web ./apps/web

RUN npm run build -w @app-ciber/web

EXPOSE 3000

CMD ["npm", "run", "start", "-w", "@app-ciber/web"]
